apiVersion: v1
kind: Pod
metadata:
  name: webapp-brahm
  namespace: webapp   
spec:
  containers:
  - image: <image-URI/path>
    name: webapp-brahm
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: <Internal-IP of mysql pod>
    - name: DBPORT
      value: "3306"
    - name: DBPWD
      value: db_pass123
    command: ["python3", "app.py"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  imagePullSecrets:
    - name: regcred     
