apiVersion: v1
kind: Pod
metadata:
  name: webapp-brahm
  namespace: webapp   
spec:
  containers:
  - image: 992332505002.dkr.ecr.us-east-1.amazonaws.com/brahm-repo-app:application-202307060227
    name: webapp-brahm
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: 10.244.0.3
    - name: DBPORT
      value: "3306"
    - name: DBPWD
      value: db_pass123
    command: ["python3", "app.py"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  imagePullSecrets:
    - name: regcred     
