apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-brahm-replicaset
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - name: webapp-brahm-replicaset
        image: 992332505002.dkr.ecr.us-east-1.amazonaws.com/brahm-repo-app:application-202307060227
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: 10.244.0.8
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: db_pass123
        command: ["python3", "app.py"]
