apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-brahm-replicaset
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - name: webapp-brahm-replicaset
        image: <image-URI/path>
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: <Internal-IP of mysql pod>
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: db_pass123
        command: ["python3", "app.py"]
