apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-brahm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-brahm-deployment
        image: 992332505002.dkr.ecr.us-east-1.amazonaws.com/brahm-repo-mysql:mysql-202307060227
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: db_pass123
